# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160424_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_address2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_address1',
            field=models.CharField(max_length=64),
        ),
    ]
