# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160424_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='age_limit',
        ),
        migrations.RemoveField(
            model_name='event',
            name='age_restriction',
        ),
        migrations.RemoveField(
            model_name='event',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='game_off',
        ),
        migrations.RemoveField(
            model_name='event',
            name='game_on',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_address1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_address2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_state',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pregens',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rules_url',
        ),
    ]
