# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160424_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default='2016-01-01'),
        ),
    ]
