# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkin',
            field=models.TimeField(blank=True, default='12:00:00.000'),
        ),
        migrations.AddField(
            model_name='event',
            name='game_off',
            field=models.TimeField(blank=True, default='12:00:00.000'),
        ),
        migrations.AddField(
            model_name='event',
            name='game_on',
            field=models.TimeField(blank=True, default='12:00:00.000'),
        ),
    ]
