# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20160424_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_limit',
            field=models.PositiveSmallIntegerField(default='18', verbose_name='Minimum age to play'),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_restriction',
            field=models.BooleanField(default=True, verbose_name='Game is restricted by age'),
        ),
        migrations.AlterField(
            model_name='event',
            name='checkin',
            field=models.TimeField(blank=True, default='12:00:00.000', verbose_name='Check-in opens'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Organizer email address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Organizer contact name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.PositiveSmallIntegerField(default='0', verbose_name='Game cost/Site fee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default='2016-01-01', verbose_name='Game Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='game_off',
            field=models.TimeField(blank=True, default='12:00:00.000', verbose_name='Game off at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='game_on',
            field=models.TimeField(blank=True, default='12:00:00.000', verbose_name='Game on at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_address1',
            field=models.CharField(blank=True, max_length=64, verbose_name='Game location address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_address2',
            field=models.CharField(blank=True, max_length=64, verbose_name='Address, cont.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_city',
            field=models.CharField(blank=True, max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_state',
            field=models.CharField(blank=True, max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='event',
            name='online_rules',
            field=models.BooleanField(default=False, verbose_name='Rules set is online'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pregens',
            field=models.BooleanField(default=False, verbose_name='Game uses pregenerated characters'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules_url',
            field=models.URLField(blank=True, verbose_name='Rules URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Game Title'),
        ),
    ]
