# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 21:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20160509_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 9, 21, 38, 6, 171494, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 9, 21, 38, 14, 779282, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
