# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20160509_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='posts',
        ),
        migrations.AddField(
            model_name='event',
            name='character_info',
            field=models.CharField(blank=True, max_length=512, verbose_name='Character Creation Info'),
        ),
        migrations.AddField(
            model_name='event',
            name='location_zip',
            field=models.CharField(blank=True, max_length=24, verbose_name='Zip/Postal Code'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='event',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='event',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='tag',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='tags', to='events.Event'),
        ),
    ]
