# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 22:54
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20160509_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='character_info',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Character Creation Info'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
