# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterField(
            model_name='event',
            name='checkin',
            field=models.TimeField(blank=True, default='12:00', verbose_name='Check-in opens'),
        ),
        migrations.AlterField(
            model_name='event',
            name='game_off',
            field=models.TimeField(blank=True, default='12:00', verbose_name='Game off at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='game_on',
            field=models.TimeField(blank=True, default='12:00', verbose_name='Game on at'),
        ),
    ]
