# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20160526_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='relationships',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='from_person',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='to_person',
        ),
        migrations.AlterField(
            model_name='player',
            name='participating_in',
            field=models.ManyToManyField(related_name='playing_in', through='events.Participation', to='events.Player'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
