# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20160526_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participation',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.DateField(default='2016-01-01', verbose_name='Player Age'),
        ),
    ]
