# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20160526_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.AddField(
            model_name='player',
            name='birthday',
            field=models.DateField(default='2016-01-01', verbose_name='Player Birthday'),
        ),
    ]
