[
    {
        "pk": 1, 
        "model": "auth.user", 
        "fields": {
            "username": "admin",
            "title": "This is a title",
            "creator": "Elaewin",
            "game_system": "MET",
            "online_rules": true,
            "rules_url": "http://www.someurl.com",
            "date": "2013-05-24T05:35:58.628Z",
            "checkin": "12:00:00.00",
            "game_on": "15:00:00.00",
            "game_off": "22:00:00.00",
            "location_address1": "12345 A Streetname",
            "location_address1": "",
            "location_city": "Seattle",
            "location_state": "WA",
            "contact_name": "Elaewin",
            "contact_email": "elaewin@gmail.com",
            "pregens": false,
            "age_restriction": false,
            "age_limit": "16",
            "cost": "25",
        }
    },
    {
        "pk": 2,
        "model": "auth.user", 
        "fields": {
            "username": "noname", 
            "first_name": "", 
            "last_name": "", 
            "is_active": true, 
            "is_superuser": true, 
            "is_staff": true, 
            "last_login": "2013-05-24T05:35:58.628Z", 
            "groups": [], 
            "user_permissions": [], 
            "email": "noname@example.com", 
            "date_joined": "2013-05-24T05:35:58.628Z"
            "title": "nogame",
            "creator": "noone",
            "game_system": "none",
            "online_rules": true,
            "rules_url": "http://www.nowhere.com",
            "date": "2013-05-24T05:35:58.628Z",
            "checkin": "01:00:00.00",
            "game_on": "01:00:00.00",
            "game_off": "01:00:00.00",
            "location_address1": "",
            "location_address1": "",
            "location_city": "",
            "location_state": "",
            "contact_name": "",
            "contact_email": "",
            "pregens": true,
            "age_restriction": true,
            "age_limit": "",
            "cost": "",
        }
    }
]